- hosts: maka-vault
  gather_facts: false
  vars_files:
       - secrets.yml
  tasks:
    - user: name=toma password={{ serverpass }}
    - user: name=vault password={{ serverpass }}
    - user: name=nginx password={{ serverpass }}
